/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inici;

import javax.swing.JOptionPane;
/**
 *
 * @author megah
 */
public class Inici extends javax.swing.JFrame {

    /**
     * Creates new form Inici
     */
    public Inici() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", null, "X", null, "X", null, "X", null},
                {null, "X", null, "X", null, "X", null, "X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"O", null, "O", null, "O", null, "O", null},
                {null, "O", null, "O", null, "O", null, "O"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Sortir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila;
        int columna;
        int numX = 0;
        int numO = 0;

        
        fila = obtenirFilaClicada();
        columna = obtenirColumnaClicada();
        
        if (noHiHaOrigen()){
            
            if (jugaX && EsX(fila,columna)){
                ActualitzaNouOrigen(fila,columna);
                                    
            }else if(jugaO && EsO(fila,columna)){
                ActualitzaNouOrigen(fila,columna);
                }else{ 
                mostraError();}
            
        }else{
            if (movimentVàlid(fila,columna)){ 
		if (esBuit(fila,columna) || OcupatContrari(fila,columna)){ 
                    mou(fila,columna);
                }else{
                    if (OcupatPropi(fila,columna)){
                        actualitzaNouOrigen(fila,columna);
                    }else{
                        mostraErrorMoviment();}
                }
                }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inici().setVisible(true);
            }
        });
    }
    
    private boolean jugaX = true;
    private boolean jugaO = false;
    private int filaOrigen = -1;
    private int columnaOrigen = -1;
    private int filaObjectiu = -1;
    private int columnaObjectiu = -1;
    
    
    private int obtenirFilaClicada(){
        return jTable1.getSelectedRow();
    }
    
    private int obtenirColumnaClicada(){
        return jTable1.getSelectedColumn();
    }
    
    private boolean noHiHaOrigen(){
        boolean noTeOrigen = false;
        if(filaOrigen == -1 ||
           columnaOrigen == -1 ){
                noTeOrigen = true;
        }
        return noTeOrigen;
    }
    
    public boolean EsX(int fila, int columna){
        boolean esx = false;
        if(jTable1.getValueAt(fila, columna) == "X"){
            esx = true;
        }
        return esx;
    }
    
    public boolean EsO(int fila, int columna){
        boolean eso = false;
        if(jTable1.getValueAt(fila, columna) == "O"){
            eso = true;
        }
        return eso;
    }
    
    public void ActualitzaNouOrigen(int fila, int columna){
        filaOrigen = fila;
        columnaOrigen = columna;
    }
    
    public void mostraError(){
        JOptionPane.showMessageDialog(null, "Error", "Chess",
                JOptionPane.ERROR_MESSAGE);
        filaOrigen = -1;
        columnaOrigen = -1;
    }
    
    public boolean movimentValid(int fila, int columna){
        boolean esMovimentValid = false;
        filaObjectiu = fila;
        columnaObjectiu = columna;
        int columnaCalculs = columnaObjectiu - columnaOrigen;
        int filaCalculs =  filaObjectiu - filaOrigen;
        
        if(jugaO && (filaCalculs == -1) && 
                ((columnaCalculs == 1) ||
                (columnaCalculs ==  -1))){
            esMovimentValid = true;
        } else if (jugaX && (filaCalculs == 1) && 
                ((columnaCalculs == 1) ||
                (columnaCalculs ==  -1))) {
            esMovimentValid = true;
        }
        
        return esMovimentValid;
    }
    
    public boolean esBuit(int fila, int columna){
        boolean estaBuit = false;
        if(jTable1.getValueAt(fila, columna) == null){
            estaBuit = true;
        }
        return estaBuit;
    }
    
    public boolean OcupatContrari(int fila, int columna){
        boolean estaOcupatContrari = false;
        if((jugaX == true && EsO(fila, columna) == true) ||
                (jugaO == true && EsX(fila, columna) == true)){
            estaOcupatContrari = true;
        }
        return estaOcupatContrari;
    }
    
    public boolean OcupatPropi(int fila, int columna) {
        boolean estaOcupatPropi = false;
        if((jugaX == true && EsX(fila, columna) == true)
                || (jugaO == true && EsO(fila, columna) == true)){
            estaOcupatPropi  = true;
        }
        
        return estaOcupatPropi;
    }
    
    public void mostraErrorMoviment() {
        JOptionPane.showMessageDialog(null, "Moviment no valid", "Chess", 
                JOptionPane.ERROR_MESSAGE);
        filaObjectiu = -1;
        columnaObjectiu = -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
